#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🚀 Running build..."
npm run build || exit 1

echo "🧪 Running tests..."
npm run test || exit 1

echo "🧠 Running typecheck..."
npm run typecheck || exit 1

echo "🔐 Running security audit..."
npm run audit || exit 1

echo "✅ Pre-push passed"