#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running build..."
npm run build

echo "Running tests..."
npm run test

echo "Running typecheck..."
npm run typecheck

echo "Running security audit..."
npm run audit